### ISSUE TITLE
feat request: Command Palette UI mode

### ISSUE THREAD

**Issue by Novaenia** [Ryhon0/TooManyBinds#1]
I've been waiting for [this mod](https://modrinth.com/mod/too-many-binds) to be updated to 1.20.6 so this is a pleasant surprise, although you may want to rename yours.

I find that the UI in this mod isn't as user-friendly as the original, which is more like a [Command Palette](https://bootcamp.uxdesign.cc/command-palette-ux-patterns-1-d6b6e68f30c1) as seen in many other software. in this mod the internal string ID of each bind is shown underneath the name, which doesn't look too great as this just doubles the size of the list being scrolled through. the original mod instead displays each bind's mod name on the right and matches them when searching.

**Comment by Ryhon0** [comment]
Oops, my bad, I didn't check if someone already made a mod with this name, I'll ask the creator of he's alright with me using that name.

I'm planning on displaying the category the keybind is in. I'll also add an option to hide the IDs.

**Comment by Ryhon0** [comment]
I've talked to the developer of Too Many Binds and was given permission to use the name, but he recommended to use a different name to avoid confusion between the two. The project's new name will be Too Many Binds Plus and all the existing links will remain the same.

I've also added support for searching by category and an option to hide the IDs in 1.1.0

![2024-05-16_13 41 20](https://github.com/Ryhon0/TooManyBinds/assets/21126698/e3b6c0ed-b5ea-4a2b-85ac-a1493ae82f92)
